version: 0.4.{build}
image: Visual Studio 2017

build:
  verbosity: minimal

init:
- git config --global core.autocrlf input

build_script:
- ps: |
    $forceVersion = @()
    if ("$env:APPVEYOR_REPO_BRANCH" -match 'v?\d*\.\d*') {
      $forceVersion = "--force-version",$env:APPVEYOR_REPO_BRANCH
    }
    .\build.cmd -t release -v "$env:APPVEYOR_BUILD_VERSION" --clean-test true $forceVersion

for:
# Publish to NuGet only from Windows on master
- branches:
    only:
    - master
    - /v?\d*\.\d*/
  artifacts:
  - path: build\*.nupkg
    name: nuget
