version: build {build}
image: Visual Studio 2017

build:
  verbosity: minimal

init:
- cmd: choco install dotnetcore-sdk --version 3.0.100-preview7-012821
- git config --global core.autocrlf input

before_build:
- ps: |
    dotnet tool install nbgv --tool-path .paket
    $env:SEMVER = .paket/nbgv get-version -v SemVer2
    Update-AppveyorBuild -Version "$env:SEMVER ($env:APPVEYOR_BUILD_ID)"

build_script:
- ps: |
    $forceVersion = @()
    if ("$env:APPVEYOR_REPO_BRANCH" -match 'v?\d*\.\d*') {
      $forceVersion = "--force-version",$env:APPVEYOR_REPO_BRANCH
    }
    .\build.cmd -t release -v "$env:SEMVER" --clean-test true $forceVersion

artifacts:
- path: build\*.nupkg
  name: nuget
