version: build {build}
image: Ubuntu

build:
  verbosity: minimal

init:
  - sudo apt update && sudo apt-get install -y dotnet-sdk-5.0
  - git config --global core.autocrlf input

before_build:
  - dotnet tool restore
  - dotnet nbgv cloud

build_script:
  - ./build.sh -t release --clean-test true

artifacts:
- path: build/*.nupkg
  name: nuget
