version: build {build}
image: Ubuntu

build:
  verbosity: minimal

init:
  - sudo apt update && sudo apt upgrade -y dotnet-sdk-3.1
  - git config --global core.autocrlf input

before_build:
  - dotnet tool restore
  - export SEMVER="$(dotnet nbgv get-version -v SemVer2)"
  - appveyor UpdateBuild -Version "$SEMVER ($APPVEYOR_BUILD_ID)"

build_script:
  - ./build.sh -t release -v "$SEMVER" --clean-test true

artifacts:
- path: build/*.nupkg
  name: nuget
